### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by HannesMorre** [wolflu05/inventree-dymo-plugin#5] opened 2024-09-10 14:12 UTC
When we try to print using this plugin, we get the following logs:
```
inventree-worker  | Failed '<bound method DymoLabelPrinterDriver.print_labels of <inventree_dymo.InvenTreeDymoPlugin.DymoLabelPrinterDriver object at 0x7ff97cef1bd0>>' (video-leopard-jupiter-jig) - '' : Traceback (most recent call last):
inventree-worker  |   File "/root/.local/lib/python3.11/site-packages/django_q/worker.py", line 97, in worker
inventree-worker  |     res = f(*task["args"], **task["kwargs"])
inventree-worker  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/InvenTreeDymoPlugin.py", line 104, in print_labels
inventree-worker  |     density=PrintDensity[machine.get_setting('DENSITY', 'D')],
inventree-worker  |             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inventree-worker  |   File "/usr/local/lib/python3.11/enum.py", line 792, in __getitem__
inventree-worker  |     return cls._member_map_[name]
inventree-worker  |            ~~~~~~~~~~~~~~~~^^^^^^
inventree-worker  | KeyError: ''
inventree-worker  | 
```

**Comment by wolflu05** [comment] 2024-09-16 18:03
Hey @HannesMorre ,

can you please provide your inventree version you're using, and a screenshot of how you configured the printer machine? And do you have explicitly configured/touched the density setting for that machine?

**Comment by HannesMorre** [comment] 2024-09-19 07:18
Here is the version information:

```
# Version Information:
InvenTree-Version: 0.16.1
Django Version: 4.2.15
Commit Hash: 4c15e5c
Commit Date: 2024-08-30

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.1.0-23-amd64-x86_64-with
Installer: DOC
```
These are the machine settings:
![image](https://github.com/user-attachments/assets/aa248c03-b7cd-4f85-81aa-3efc537649ab)

This is the pop-up we get when we try to print from the platform UI:
![image](https://github.com/user-attachments/assets/cc6a3f00-a569-4fd6-9be7-6801530c09c1)

Nothing is printed despite the "Success" notification

**Comment by wolflu05** [comment] 2024-09-19 16:07
Hi @HannesMorre 

The Error message you are seeing is currently actually expected for physical printers, as they run in the background and return a `completed: false`. This is still WIP on the inventree side in PUI, but should not block you from printing. Ref: https://github.com/InvenTree/InvenTree/blob/d59ce49d8230ad8036fae10b0f46a0d352ebfc56/src/frontend/src/components/buttons/PrintingActions.tsx#L103-L111

It seems that the "Print Mode" and "Print Density" settings were not set somehow by their defaults. I have tried to reproduce this on a fresh docker setup using `inventree/inventree:0.16.1`, but I'm not able to do so. So I have a few ideas you could try:

1. Make sure you have a Redis cache configured, as machines will only work with a Redis cache
2. Try creating a new machine and see if those two settings are configured then? By default they should be density: Normal a mode:TEXT.
3. If that still does not work, try to set them manually to their default (Normal and Text)
4. If that error from your initial comment (KeyError: '') is not present anymore, but there is still nothing printed make sure that you can reach your printer server `172.16.128.20` from within the container. (`docker exec -it <worker-container> ash` and then try `ping 172.16.128.20`) Maybe your docker network uses the same network as your local network .
5. Try running a netcat server in your worker container via `docker exec -it <worker-container> ash` and then `nc -l -p 9100`. Then you need to configure the printing machine to use localhost and port 9100. When printing, this should output something. You can even check if it outputs something correct by running `nc -l -p 9100 > test.bin`, print again, and then `python /usr/local/lib/python3.11/site-packages/inventree_dymo/dymo_to_png.py test.bin text`. If you see an image with lots of `#` and ` ` and no error, everything worked fine. (You may need to disable line wrap and zoom out of your terminal). (FYI, if you want an png image, you need to change the last line of that python script from `out.show()` to `out.save("/tmp/img.png")` and run with `python dymo_to_png.py test.bin image`).
6. If nothing helps, please enable debug mode and provide any log output you can get from the worker and server container
7. which plugin version are you running?

**Comment by wolflu05** [comment] 2024-09-26 08:16
@HannesMorre Did you found the issue?

**Comment by lqdmist** [comment] 2024-09-26 14:51
Hi, I am a co-worker of @HannesMorre.
We found out our inventree server is unable to reach the print server, so this issue is on our side.
We are currently unable to test since we need to move our server to a different vlan but this is hindered by a couple of factors.
In case we are able to test it, we will reply on this ticket if the issue still persists. You can close it for now

**Comment by wolflu05** [comment] 2024-09-27 05:46
Ok, thanks for your response.

**Comment by HannesMorre** [comment] 2024-11-12 14:55
HI @wolflu05 we are trying again to get this plugin working. This time we are encountering different issues:
```
inventree-server  | 172.16.128.128 - - [12/Nov/2024:15:51:14 +0100] "GET /api/notifications/?read=false&limit=1 HTTP/1.0" 200 442 "https://inventree-staging.unmatched.eu/platform/stock/location/index/stock-items" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
inventree-worker  | Failed '<bound method DymoLabelPrinterDriver.print_labels of <inventree_dymo.InvenTreeDymoPlugin.DymoLabelPrinterDriver object at 0x7f9b32d23390>>' (south-lemon-skylark-maryland) - 'str' object has no attribute 'to_bytes' : Traceback (most recent call last):
inventree-worker  |   File "/root/.local/lib/python3.11/site-packages/django_q/worker.py", line 97, in worker
inventree-worker  |     res = f(*task["args"], **task["kwargs"])
inventree-worker  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/InvenTreeDymoPlugin.py", line 101, in print_labels
inventree-worker  |     dymo_label = DymoLabel(
inventree-worker  |                  ^^^^^^^^^^
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/dymo.py", line 240, in __init__
inventree-worker  |     super().__init__(compressed, rotate, threshold)
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/dymo.py", line 137, in __init__
inventree-worker  |     self.init_job()
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/dymo.py", line 245, in init_job
inventree-worker  |     self.pb.set_label_length(self.label_length)
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/dymo.py", line 75, in set_label_length
inventree-worker  |     self.raw([0x1b, ord("L"), *self._to_bytes(length)])
inventree-worker  |                                ^^^^^^^^^^^^^^^^^^^^^^
inventree-worker  |   File "/usr/local/lib/python3.11/site-packages/inventree_dymo/dymo.py", line 59, in _to_bytes
inventree-worker  |     return value.to_bytes(2, 'big', signed=True)
inventree-worker  |            ^^^^^^^^^^^^^^
inventree-worker  | AttributeError: 'str' object has no attribute 'to_bytes'
```

**Comment by wolflu05** [comment] 2024-11-12 15:10
Hi, this error may occur, if the label you are trying to print is bigger than the maximum width of a label which can be printed. Or maybe also longer? This may occur if it's rotated the wrong way. So I suggest trying out to rotate the label.

If that does not work, please try a smaller label template e.g. 10mmx10mm just for the test, if printing works at all.

**Comment by HannesMorre** [comment] 2024-11-12 15:25
With the label template size set to 10mm x 10mm and rotation at 180° we still get the same error

**Comment by wolflu05** [comment] 2024-11-12 15:42
Oh sorry, I should have read the error more carefully. What I was describing is the solution to a similar error text, but different problem.

Your issue is something different. What version of inventree are you running? And if you're using a worker (default production setup) do you use a shared cache (redis) [like required](https://docs.inventree.org/en/stable/extend/machines/overview/#machines) for the machine printing feature?

**Comment by HannesMorre** [comment] 2024-11-12 16:02
@lqdmist can you answer this?

**Comment by lqdmist** [comment] 2024-11-12 16:12
We are running 0.16.1 both in our staging and production environment. I installed a redis container and added those settings to the environment of the inventree server:
``` bash
INVENTREE_CACHE_ENABLED=True
INVENTREE_CACHE_HOST=inventree-cache
INVENTREE_CACHE_PORT=6379
```
``` bash
    inventree-cache:
        image: redis:7.0
        container_name: inventree-cache
        restart: always
        ports:
          - "6378:6379"
        networks:
          inventree-default:
```

**Comment by wolflu05** [comment] 2024-11-12 16:27
That's interesting, with those settings it should work. Have you restarted the server, and you are sure that the redis cache is used?

(The issue is, that the machine instance is shared through the cache between the main process and the workers. When the worker tries to print, it tries to load that machine instance + list of all settings from the cache and uses this to correctly parse (str is stored in db, but setting for label length should be a number, so we can call `.to_bytes()`) the values provided via settings).

Can you please also post a screenshot of how you have configured the dymo printing machine?

**Comment by HannesMorre** [comment] 2024-11-13 06:35
Here is the screenshot: 
![image](https://github.com/user-attachments/assets/a0bd9ced-f4ce-43be-8e4c-172ab06bda15)

**Comment by lqdmist** [comment] 2024-11-13 08:15
I see SET and GET items in the redis logging using `redis-cli` so I suppose it is working:
``` bash
user@staging$ docker exec -it inventree-cache redis-cli
127.0.0.1:6379> MONITOR
OK
1731485615.323205 [0 172.24.0.5:43418] "GET" ":1:django_q:InvenTree:cluster"
1731485615.323788 [0 172.24.0.5:43418] "SET" ":1:django_q:InvenTree:cluster" "\x80\x04\x95F\x00\x00\x00\x00\x00\x00\x00]\x94\x8c?django_q:InvenTree:cluster:f9fb16c9-c488-43e8-9192-2f5083518e1a\x94a." "PX" "300000"
1731485615.324235 [0 172.24.0.5:43418] "SET" ":1:django_q:InvenTree:cluster:f9fb16c9-c488-43e8-9192-2f5083518e1a" "\x80\x04\x95S\x02\x00\x00\x00\x00\x00\x00XL\x02\x00\x00.eJxVUc9LXDEQXtmn-3ZXLcXSilcvK4W1pWjr2V7kXfoDj_LIey_1xc0mz2RCdUGwFLXIILSO_4S11T_Ci_-JPfVc6qHJimAThsyXyWTm-2Z39OT3SG248EGxwdS6Tje7Fhg4Sxi99w4d09wn2qEONj5q0-PG0hp1ku_JWfIj-cmxDjojjAsGHESf33ePabnVuG6PT85PN5sbVMYYh_uBViHmYTPAgktgHie1sA_oHe152_eGk4YLlTOjGAitrH-C9UoUlDzFVi6dBW5SDzFybnisrq68vusX60IBHT6cOXr7-c38t6_Xy18urx7__VOzGcaWKxCKS0pOceyO7pNbAboOhLTdD07loSqThI9SyQbbaWX01nbqVCXyngwUOjj9Xw4YpqwcNkvYWOcAfCsIiNFK4RP2Qltx5oT0xX3BugXjoxCotguvSrqZWjHggWdUaguE4xl7_uLZq8WlhcX8pf-zr5UAbSg5xzYw27uXMVY5W3IfurjV1dPqV1S2hjOYiCdmo183VE4FYV3W_QftNMhH:1tB8VL:WEMu60gtsJdIML2V0g9Aj9iJ0Mht7tisGRx1WaP1zn4\x94." "PX" "3000"
1731485615.825740 [0 172.24.0.5:43418] "GET" ":1:django_q:InvenTree:cluster"

```

**Comment by wolflu05** [comment] 2024-11-14 10:15
That's interesting it should work, I will have to find some time to try to reproduce this myself.

**Comment by wolflu05** [comment] 2024-11-17 19:21
I have tested this with the newest stable versions (inventree: 0.16.8, inventree-dymo-plugin: 1.0.0) now and I'm not able to reproduce this. I just used the default docker setup, just added the redis cache and setup a superuser account. Then installed the plugin created a dymo machine and tried to print a template (20x20mm, the default width of 50mm does not work, there is no such big dymo printer).

Regarding the redis `MONITOR`. Do you see things like `:1:machine:*` (e.g. `:1:machine:registry:hash` or `:1:machine:machine:<machine-uuid>:status`, they should definitely show up when doing something with the machines, e.g. load the machine table)

**Comment by wolflu05** [comment] 2024-11-25 18:20
I'm closing this due to no response, if you still have this issue, feel free to reopen it with more context and the steps you have tried.

**Closed as not planned by wolflu05** 2024-11-25 18:20 UTC
Labels: question, type/setup
